title: Ragunath Gunasekaran # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist - AI & ML
  
  <br><br>
  Data / BI Arichitect - Big Data, MS Power BI, SQL, SSAS Cube,  
  <br><br>
  
  <a href="https://www.linkedin.com/in/ragunath-gunasekaran-30130663/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
